### ISSUE TITLE
version numbers must be collected into one place

### ISSUE THREAD

**Issue by usta** [edwardgeorge/virtualenv-clone#44]
Hello, right now package version info and py version info is  not same and all version numbers are needed to change when a bump needed.
So my suggestion is to collect all these info to a seperate file lets name it __version__.py and in that file a variable for example version  , and in whole other places ( in setup.py , in main app py   , ... ) Ve use that variable that will let us fix all version related problems

**Comment by timabbott** [comment]
Adding a `version.py` sounds good to me.

**Comment by usta** [comment]
this fix doesn't need any release, I mean after this fix you can wait for another important fix to release a 0.5.1 or 0.6.0, This will be just  a trivial fix

**Comment by eeshangarg** [comment]
@usta: Hey! Actually, we can't have a `version.py` file because the package only exports one file when the package is installed, which is `clonevirtualenv.py`. So any dependency on an external file that isn't a part of the installed files will break the package. Or, in other words, once the `clonevirtualenv.py` file is installed, it can't find the `version.py` file anymore, because it isn't a part of the installed files. :) With my experience maintaining packages, I feel that it is better to just update the version number in two places than having a submodule with an `__init__.py` file just so that we can include a `version.py` file. Thanks a lot for reporting! Just fixed this in #46 and I'll make a quick release right after! :)

**Comment by usta** [comment]
To be honest this report was all about fixing #46 (which that pr doesnt exist in that time) so right now we can close this issue as fixed i think :)

**Comment by eeshangarg** [comment]
@timabbott, @usta: Just made a new release! :)
